# Generated by Django 4.2.3 on 2023-08-03 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0003_alter_products_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='category',
        ),
        migrations.AddField(
            model_name='products',
            name='categories',
            field=models.ManyToManyField(related_name='products', to='ecomapp.category'),
        ),
    ]
