# Generated by Django 4.2.3 on 2023-08-04 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0004_remove_products_category_products_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='categories',
            new_name='category',
        ),
    ]
