# Generated by Django 4.2.4 on 2023-08-20 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0011_orderitem_price_at_order_creation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='price_at_order_creation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='ecomapp.products'),
        ),
    ]
