# Generated by Django 4.2.4 on 2023-08-20 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0012_alter_orderitem_price_at_order_creation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='price_at_order_creation',
        ),
    ]
